apiVersion: v1
kind: ConfigMap
metadata:
  name: fiapx-config
  namespace: default
data:
  DB_URL: "jdbc:postgresql://postgres-service:5432/fiapx_db"
  DB_USER: "fiapx_user"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  STORAGE_PATH: "/app/storage_data"
  WORKER_CONCURRENCY: "4"
  WORKER_MAX_CONCURRENCY: "8"
