apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-x-processor
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiap-x-processor
  template:
    metadata:
      labels:
        app: fiap-x-processor
    spec:
      containers:
        - name: fiap-x-processor
          image: fiapx/fiap-x-video-processor:latest
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: fiapx-config
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: fiapx-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiapx-secrets
                  key: DB_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: fiapx-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: fiapx-config
                  key: RABBITMQ_PORT
            - name: STORAGE_PATH
              valueFrom:
                configMapKeyRef:
                  name: fiapx-config
                  key: STORAGE_PATH
            - name: WORKER_CONCURRENCY
              valueFrom:
                configMapKeyRef:
                  name: fiapx-config
                  key: WORKER_CONCURRENCY
            - name: WORKER_MAX_CONCURRENCY
              valueFrom:
                configMapKeyRef:
                  name: fiapx-config
                  key: WORKER_MAX_CONCURRENCY
          volumeMounts:
            - name: storage-volume
              mountPath: /app/storage_data
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: fiapx-storage-pvc
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fiap-x-processor-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiap-x-processor
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
