apiVersion: v1
kind: Secret
metadata:
  name: fiapx-secrets
  namespace: default
type: Opaque
stringData:
  DB_PASSWORD: "fiapx_secure_password_2026"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  RABBITMQ_PASSWORD: "guest"
